source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/kaandedeoglu/KDCircularProgress.git'
use_frameworks!

pod 'KDCircularProgress'
target 'KKCircularProgressView_Example', :exclusive => true do
  pod 'KKCircularProgressView', :path => '../'
end

target 'KKCircularProgressView_Tests', :exclusive => true do
  pod 'KKCircularProgressView', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'KDCircularProgress'

end
